      !DEC$ ATTRIBUTES DLLEXPORT::DLSODEINTEROP
      SUBROUTINE DLSODEINTEROP (F, NEQ, Y, T, TOUT, ITOL, RTOL, ATOL,
     1       ITASK, ISTATE, IOPT, RWORK, LRW, IWORK, LIW, JAC, MF)
      EXTERNAL F, JAC
      INTEGER NEQ, ITOL, ITASK, ISTATE, IOPT, LRW, IWORK, LIW, MF
      DOUBLE PRECISION Y, T, TOUT, RTOL, ATOL, RWORK
      DIMENSION NEQ(*), Y(*), RTOL(*), ATOL(*), RWORK(LRW), IWORK(LIW)

      CALL DLSODE (F, NEQ, Y, T, TOUT, ITOL, RTOL, ATOL, ITASK,
     1          ISTATE, IOPT, RWORK, LRW, IWORK, LIW, JAC, MF)

      END
